#!/usr/bin/perl
use strict;
use warnings;
use integer;
require 5.8.0;

use Carp 'cluck';
use POSIX;
use IO::Handle;
use IO::Socket::SSL;
use IO::Socket::INET;
use Socket;
use Scalar::Util qw(weaken tainted);
use Fcntl;
use overload;

eval {
	require IO::Socket::INET6;
	require Socket6;
	1;
} or print "IPv6 not available\n";

eval {
	require Net::DNS;
	1;
} or print "DNS lookups not available\n";

print "All required modules found\n";
