#!/usr/bin/perl
use strict;
use warnings;
use integer;
require 5.8.0;

use Carp 'cluck';
use POSIX;
use IO::Handle;
use IO::Socket::INET;
use Socket;
use Scalar::Util qw(weaken tainted);
use Fcntl;
use overload;

print "SSL: ", eval {
	require IO::Socket::SSL;
	1;
} ? "OK\n" : "Not available\n";

print "IPv6: ", eval {
	require IO::Socket::INET6;
	require Socket6;
	1;
} ? "OK\n" : "Not available\n";

print "DNS: ", eval {
	require Net::DNS;
	1;
} ? "OK\n" : "Not available\n";

print "All required modules found.\n";
