#!/usr/bin/perl -T
use strict;
use warnings;
use integer;
use constant TEST => 1;
use overload;
require 5.8.0;

use Carp 'cluck';
use POSIX;
use IO::Handle;
use Socket;
use Scalar::Util qw(weaken tainted);
use Fcntl;
eval { require Digest::SHA; 1 } || eval { require Digest::SHA1; 1 } ||
	die "One of Digest::SHA or Digest::SHA1 is required";

print "SSL: ", eval {
	require IO::Socket::SSL;
	1;
} ? "OK\n" : "Not available (install IO::Socket::SSL)\n";

print "IPv6: ", eval {
	require Socket6;
	require IO::Socket::INET6;
	1;
} ? "OK\n" : "Not available (install IO::Socket::INET6)\n";

print "DNS: ", eval {
	require Net::DNS;
	1;
} ? "OK\n" : "Not available (install Net::DNS)\n";

print "All required modules found.\n";
